const funnyTexts = [
  // Short fragments & random words
  'suspicious waffles',
  'aggressively mediocre',
  'chaotic neutral energy',
  'legally questionable',
  'mildly threatening aura',
  'unhinged but polite',
  'feral with good intentions',
  'professionally confused',
  'emotionally unavailable lasagna',
  'menacingly wholesome',
  'unregistered wizard',
  'turbulent juice',
  'forbidden knowledge (recipe)',
  'sentient spreadsheet',
  'vaguely threatening potato',
  'absolute unit of a QR code',
  'controlled chaos',
  'accidental genius',
  'weaponized incompetence',
  'bureaucratic nightmare fuel',
  'unlicensed therapist vibes',
  'dangerously cheesy',
  'audibly confused',
  'strategic napping',
  'nonchalant screaming',
  'optimistic dumpster fire',

  // Short sentences
  'Error 404: motivation not found',
  'sudo make me a sandwich',
  'rm -rf /my-problems',
  'Works on my machine',
  'I should be sleeping right now',
  'Not my circus, not my monkeys',
  'This QR code does nothing useful',
  'Do not scan. Oh wait, too late.',
  'Plot twist: this QR code scans YOU',
  'Powered by spite and caffeine',
  'This meeting could have been a QR code',
  'My password is password123',
  'I blame the intern',
  'Instructions unclear, made a QR code',
  'Certified organic, gluten-free QR code',
  'Made with recycled pixels',
  'It compiles, ship it',
  'Trust me, I am an engineer',
  'git push --force and pray',
  'TODO: write something funny here',
  'This is fine. Everything is fine.',
  'Ask me about my mass unsubscribe',
  'Scanned by someone with great taste',
  'My other QR code is a barcode',
  'Not all who scan are lost',
  'Keep calm and clear your cache',
  'Feature, not a bug',
  'I googled the error message too',
  'Loading personality... please wait',
  'Reply hazy, try again later',
  'Existence is mandatory',
  'Brought to you by bad decisions',
  'Handle with mild concern',
  'May cause spontaneous snacking',
  'This is my emotional support QR code',
  'The WiFi password is on the other fridge',
  'Abandon all hope, ye who scan here',
  'I peaked in the tutorial level',
  'Please do not feed the developers',
  'Left on read by my own code',
  'My code works and I have no idea why',
  'Today is a good day to refactor nothing',
  'I whisper to my bugs at night',
  'The cloud is just someone else\'s computer',
  'Deploying on Friday? Bold move.',
  'No thoughts, just vibes and semicolons',
  'One does not simply scan a QR code',
  'Mildly cursed but mostly functional',
  'Do not pet the production server',
  'Warranty void if scanned',
  'Contains no actual information',
  'Technically correct, the best kind',
  'Shh, the code is sleeping',
  'You have been mildly inconvenienced',
  'Congratulations, you unlocked nothing',
  'New phone, who dis',
  'Alexa, write my code',
  'That\'s a problem for future me',
  'If lost, return to coffee shop',
  'No refunds on scanned QR codes',
  'I was told there would be snacks',
  'Runs on vibes and duct tape',
];

const funnyUrls = [
  'https://example.com/definitely-not-a-rickroll',
  'https://example.com/free-wifi-just-kidding',
  'https://example.com/the-meaning-of-life',
  'https://example.com/404-happiness-not-found',
  'https://example.com/my-cats-resume',
  'https://example.com/worlds-okayest-website',
  'https://example.com/click-here-for-nothing',
  'https://example.com/i-should-be-working',
  'https://example.com/another-todo-app',
  'https://example.com/professional-procrastinator',
  'https://example.com/send-pizza',
  'https://example.com/is-it-friday-yet',
  'https://example.com/who-needs-sleep',
  'https://example.com/deploy-on-friday',
  'https://example.com/works-on-my-machine',
  'https://example.com/stackoverflow-saved-me',
  'https://example.com/not-a-virus-i-promise',
  'https://example.com/under-construction-since-1999',
  'https://example.com/the-last-website',
  'https://example.com/trust-me-im-a-url',
];

function randomFrom<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

export function generateRandomPhrase(): string {
  return randomFrom(funnyTexts);
}

export function generateRandomUrl(): string {
  return randomFrom(funnyUrls);
}
